spring:
  application:
    name: secure-server

server:
  port: 8443
  ssl:
    key-store: classpath:server-keystore.p12
    key-store-password: secret
    key-alias: secure-server
    trust-store: classpath:server-truststore.p12
    trust-store-password: secret
    enabled: true
    client-auth: need
    trust-store-type: PKCS12

logging:
  level:
    org.springframework.security: DEBUG